### ISSUE TITLE
Network unreachable error with Numan One

### ISSUE THREAD

**Issue by wotaen** [huaracheguarache/Frontier-Silicon-Argon-Firmware#3]
This isn't an issue with this repo, but something I'm experiencing with the firmware on Numan One. So maybe you know about it...

When I play audio via DLNA, it stops after a minute and the radio says "Network unreachable" even if it had full signal just a second ago. It won't recover and I need to go to list of networks and do some discovery and the network comes up eventually.

I also have one of Hama's radios with the same firmware and I doesn't have that issue.

Please let me know to michal@holub.pro if you happen to know more. Feel free to close this issue.

Thanks,

Michal

**Comment by huaracheguarache** [comment]
I'm sorry, but I don't know anything about this issue.
